fix: load ::common::monitor::prometheus::server and ::common::monitor::exporter from common::monitor::prometheus class, so node_exporter does not fail with wierd error
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Prometheus]:
  expects a value for parameter env_file_path
  parameter init_style expects a match for Prometheus::Initstyle = Enum[launchd, none, sles, systemd, sysv, upstart], got init (file: /etc/puppetlabs/code/environments/arm64_support/modules/enableit/common/manifests/monitor/exporter/node.pp, line: 167, column: 3) on node
```