fix: installed ruby packages for TurrisOS and fixed the version for it too.
```
gem install -v 8.23.0 --no-document openvox
ERROR:  Error installing openvox:
        openvox-8.23.0 requires Ruby version >= 3.1.0. The current ruby version is 3.0.6.216.

```

And turris comes with 3.0 ruby version, and 7.x of openvox support 2.5